# Generated by Django 5.2.17 on 2026-09-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_pix', models.CharField(max_length=150)),
                ('tipo_pix', models.CharField(choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('aleatoria', 'Chave Aleatória')], max_length=20)),
                ('nome_banco', models.CharField(max_length=100)),
                ('numero_conta', models.CharField(max_length=30)),
                ('codigo_conta', models.CharField(blank=True, max_length=30)),
                ('agencia', models.CharField(max_length=20)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Horários',
                'ordering': ['data', 'horario_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_procedimento', models.CharField(max_length=150)),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('especialidade', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('especialidade', models.CharField(max_length=100)),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos', to='agendas.contabancaria')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concierge', models.CharField(blank=True, max_length=150)),
                ('tipo_calculo_pagamento', models.BooleanField(default=True, help_text='True = Por Procedimento, False = Por Paciente')),
                ('valor_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confirmacao_medico', models.BooleanField(default=False)),
                ('horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='agendas.horario')),
                ('medico_atendido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas_atendidas', to='agendas.medico')),
                ('medico_inicial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas_iniciais', to='agendas.medico')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esperanca_pacientes', models.PositiveIntegerField(default=1)),
                ('real_pacientes', models.PositiveIntegerField(blank=True, null=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.agenda')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.procedimento')),
            ],
            options={
                'verbose_name': 'Procedimento da Agenda',
                'verbose_name_plural': 'Procedimentos da Agenda',
            },
        ),
        migrations.AddField(
            model_name='agenda',
            name='procedimentos',
            field=models.ManyToManyField(related_name='agendas', through='agendas.ProcedimentoAgenda', to='agendas.procedimento'),
        ),
        migrations.CreateModel(
            name='SalaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.horario')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.sala')),
            ],
            options={
                'verbose_name': 'Sala x Horário',
                'verbose_name_plural': 'Sala x Horário',
                'unique_together': {('sala', 'horario')},
            },
        ),
        migrations.AddField(
            model_name='horario',
            name='salas',
            field=models.ManyToManyField(related_name='horarios', through='agendas.SalaHorario', to='agendas.sala'),
        ),
        migrations.AddField(
            model_name='sala',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='agendas.unidade'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='agendas.unidade'),
        ),
        migrations.CreateModel(
            name='UnidadeMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.medico')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.unidade')),
            ],
            options={
                'verbose_name': 'Unidade x Médico',
                'verbose_name_plural': 'Unidade x Médico',
                'unique_together': {('unidade', 'medico')},
            },
        ),
        migrations.AddField(
            model_name='medico',
            name='unidades',
            field=models.ManyToManyField(related_name='medicos', through='agendas.UnidadeMedico', to='agendas.unidade'),
        ),
    ]
