# Generated by Django 5.2.17 on 2026-09-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='valor_real',
        ),
    ]
