# Generated by Django 5.2.17 on 2026-10-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_remove_agenda_valor_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('dia_semana', models.PositiveSmallIntegerField(help_text='0 = Segunda ... 6 = Domingo')),
                ('intervalo_semanas', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Recorrência',
                'verbose_name_plural': 'Recorrências',
            },
        ),
        migrations.AddField(
            model_name='agenda',
            name='recorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas', to='agendas.recorrencia'),
        ),
    ]
