# Generated by Django 5.2.17 on 2026-10-06 15:18

from django.db import migrations, models
from django.db.models import F


def preencher_status(apps, schema_editor):
    """Deduz o status do médico inicial a partir de medico_atendido/confirmacao_medico."""
    Agenda = apps.get_model("agendas", "Agenda")
    com_inicial = Agenda.objects.filter(medico_inicial__isnull=False)
    # Substituto alocado => o inicial cancelou.
    com_inicial.filter(medico_atendido__isnull=False).exclude(medico_atendido=F("medico_inicial")).update(
        status_medico_inicial="cancelado"
    )
    com_inicial.filter(medico_atendido=F("medico_inicial"), confirmacao_medico=True).update(
        status_medico_inicial="confirmado"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_recorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='status_medico_inicial',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.RunPython(preencher_status, migrations.RunPython.noop),
    ]
