# Generated by Django 5.2.17 on 2026-10-06 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0004_status_medico_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario_nome', models.CharField(max_length=150)),
                ('usuario_cargo', models.CharField(blank=True, max_length=50)),
                ('acao', models.CharField(choices=[('cadastro', 'Cadastro'), ('modificacao', 'Modificação'), ('exclusao', 'Exclusão')], max_length=20)),
                ('agenda_numero', models.PositiveIntegerField(blank=True, null=True)),
                ('resumo', models.CharField(max_length=255)),
                ('alteracoes', models.JSONField(default=list, help_text='Lista de {"campo", "antes", "depois"}')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agendas.unidade')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_agenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Agenda',
                'verbose_name_plural': 'Histórico de Agendas',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
