# Generated by Django 5.2.17 on 2026-10-08 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0005_log_agenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='tipo_calculo_pagamento',
        ),
        migrations.AddField(
            model_name='agenda',
            name='hora_chegada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='hora_saida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='realizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='realizada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='realizada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='medico_exclusivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos_exclusivos', to='agendas.medico'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='prazo_repasse_meses',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mês seguinte'), (3, 'Em 3 meses')], default=1, help_text='Meses após o mês do atendimento em que o médico recebe.'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='tipo_calculo',
            field=models.CharField(choices=[('procedimento', 'Por procedimento'), ('paciente', 'Por paciente')], default='procedimento', help_text='Por procedimento: o médico recebe o valor base uma vez. Por paciente: valor base × pacientes.', max_length=20),
        ),
        migrations.CreateModel(
            name='FechamentoRepasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Dia 1 do mês em que o repasse é pago.')),
                ('status', models.CharField(choices=[('fechado', 'Fechado'), ('pago', 'Pago')], default='fechado', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fechado_em', models.DateTimeField(auto_now_add=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_repasse', to='agendas.medico')),
                ('pago_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fechamento de Repasse',
                'verbose_name_plural': 'Fechamentos de Repasse',
                'ordering': ['-competencia', 'medico__nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemRepasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_numero', models.PositiveIntegerField(blank=True, null=True)),
                ('data_atendimento', models.DateField()),
                ('unidade_nome', models.CharField(blank=True, max_length=150)),
                ('procedimento_nome', models.CharField(max_length=150)),
                ('tipo_calculo', models.CharField(choices=[('procedimento', 'Por procedimento'), ('paciente', 'Por paciente')], max_length=20)),
                ('prazo_repasse_meses', models.PositiveSmallIntegerField()),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='agendas.fechamentorepasse')),
                ('procedimento_agenda', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_repasse', to='agendas.procedimentoagenda')),
            ],
            options={
                'verbose_name': 'Item de Repasse',
                'verbose_name_plural': 'Itens de Repasse',
                'ordering': ['data_atendimento', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='fechamentorepasse',
            constraint=models.UniqueConstraint(fields=('medico', 'competencia'), name='unico_fechamento_medico_mes'),
        ),
    ]
